//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shapeshifter.Desktop.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shapeshifter.Desktop.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapeshifter can&apos;t access the clipboard because {0} is using it. Try shutting down remote desktop connections or interfering firewalls and try again..
        /// </summary>
        public static string BalloonTipClipboardDisturbanceContent {
            get {
                return ResourceManager.GetString("BalloonTipClipboardDisturbanceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something else is using the clipboard.
        /// </summary>
        public static string BalloonTipClipboardDisturbanceTitle {
            get {
                return ResourceManager.GetString("BalloonTipClipboardDisturbanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapeshifter has been updated to version {0}. Click this balloon tip to apply the update now. If you choose not to do so, the update will be applied the next time Shapeshifter restarts..
        /// </summary>
        public static string BalloonTipPendingUpdateContent {
            get {
                return ResourceManager.GetString("BalloonTipPendingUpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending update.
        /// </summary>
        public static string BalloonTipPendingUpdateTitle {
            get {
                return ResourceManager.GetString("BalloonTipPendingUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click this tray icon for settings and more..
        /// </summary>
        public static string BalloonTipSettingsContent {
            get {
                return ResourceManager.GetString("BalloonTipSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapeshifter settings.
        /// </summary>
        public static string BalloonTipSettingsTitle {
            get {
                return ResourceManager.GetString("BalloonTipSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to make Shapeshifter available in every language possible, and there are only {0} untranslated phrases remaining in {1}. Right-click this tray-icon and click &quot;{2}&quot; to get started..
        /// </summary>
        public static string BalloonTipTranslationHelpNeededContent {
            get {
                return ResourceManager.GetString("BalloonTipTranslationHelpNeededContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need your help translating!.
        /// </summary>
        public static string BalloonTipTranslationHelpNeededTitle {
            get {
                return ResourceManager.GetString("BalloonTipTranslationHelpNeededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use Crowdin to translate our software and website. You will now be taken to the Flamefusion project on Crowdin, where you can find and create Shapeshifter translations..
        /// </summary>
        public static string MessageBoxCrowdinContent {
            get {
                return ResourceManager.GetString("MessageBoxCrowdinContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be taken to Crowdin.
        /// </summary>
        public static string MessageBoxCrowdinTitle {
            get {
                return ResourceManager.GetString("MessageBoxCrowdinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incineration has now been enabled and has kicked in. A total of {0} megabytes memory was freed.
        ///
        ///Shapeshifter now consumes approximately {1} megabytes of memory..
        /// </summary>
        public static string MessageBoxIncinerationInitiatedContent {
            get {
                return ResourceManager.GetString("MessageBoxIncinerationInitiatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incineration initiated.
        /// </summary>
        public static string MessageBoxIncinerationInitiatedTitle {
            get {
                return ResourceManager.GetString("MessageBoxIncinerationInitiatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart Shapeshifter for this setting to apply..
        /// </summary>
        public static string MessageBoxRestartShapeshifterContent {
            get {
                return ResourceManager.GetString("MessageBoxRestartShapeshifterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Shapeshifter.
        /// </summary>
        public static string MessageBoxRestartShapeshifterTitle {
            get {
                return ResourceManager.GetString("MessageBoxRestartShapeshifterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, you&apos;re done!
        ///
        ///However, please take a look at our settings. You will be presented with them now, but can choose to close them down.
        ///
        ///Note that you can also access these settings later by right-clicking the Shapeshifter tray icon..
        /// </summary>
        public static string MessageBoxSeeSettingsContent {
            get {
                return ResourceManager.GetString("MessageBoxSeeSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re done!.
        /// </summary>
        public static string MessageBoxSeeSettingsTitle {
            get {
                return ResourceManager.GetString("MessageBoxSeeSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapeshifter has detected that an uninstallation was executed. All remaining files that were in use during the installation process have been removed..
        /// </summary>
        public static string MessageBoxShapeshifterUninstalledContent {
            get {
                return ResourceManager.GetString("MessageBoxShapeshifterUninstalledContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapeshifter uninstall complete.
        /// </summary>
        public static string MessageBoxShapeshifterUninstalledTitle {
            get {
                return ResourceManager.GetString("MessageBoxShapeshifterUninstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsClose {
            get {
                return ResourceManager.GetString("SettingsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows&apos; Aero color from the Windows personalization control panel (Windows Vista or higher).
        /// </summary>
        public static string SettingsDesignAndLayoutColorAeroContent {
            get {
                return ResourceManager.GetString("SettingsDesignAndLayoutColorAeroContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string SettingsDesignAndLayoutColorBlue {
            get {
                return ResourceManager.GetString("SettingsDesignAndLayoutColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the color that is used for selected items, around borders and as shadows..
        /// </summary>
        public static string SettingsDesignAndLayoutColorContent {
            get {
                return ResourceManager.GetString("SettingsDesignAndLayoutColorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string SettingsDesignAndLayoutColorGreen {
            get {
                return ResourceManager.GetString("SettingsDesignAndLayoutColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string SettingsDesignAndLayoutColorRed {
            get {
                return ResourceManager.GetString("SettingsDesignAndLayoutColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string SettingsDesignAndLayoutColorTitle {
            get {
                return ResourceManager.GetString("SettingsDesignAndLayoutColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you can change the user interface language used in Shapeshifter. Per default, the language for your keyboard layout is used..
        /// </summary>
        public static string SettingsDesignAndLayoutLanguageContent {
            get {
                return ResourceManager.GetString("SettingsDesignAndLayoutLanguageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsDesignAndLayoutLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsDesignAndLayoutLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design &amp; layout.
        /// </summary>
        public static string SettingsDesignAndLayoutTitle {
            get {
                return ResourceManager.GetString("SettingsDesignAndLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can configure which way you want to interact with Shapeshifter..
        /// </summary>
        public static string SettingsMiscellaneousInteractionSettingsContent {
            get {
                return ResourceManager.GetString("SettingsMiscellaneousInteractionSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External mode (best for mouse users).
        /// </summary>
        public static string SettingsMiscellaneousInteractionSettingsExternalMode {
            get {
                return ResourceManager.GetString("SettingsMiscellaneousInteractionSettingsExternalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated mode (best for CTRL + C and CTRL + V users).
        /// </summary>
        public static string SettingsMiscellaneousInteractionSettingsIntegratedMode {
            get {
                return ResourceManager.GetString("SettingsMiscellaneousInteractionSettingsIntegratedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed mode.
        /// </summary>
        public static string SettingsMiscellaneousInteractionSettingsMixedMode {
            get {
                return ResourceManager.GetString("SettingsMiscellaneousInteractionSettingsMixedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction settings.
        /// </summary>
        public static string SettingsMiscellaneousInteractionSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsMiscellaneousInteractionSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you can configure how Shapeshifter starts up..
        /// </summary>
        public static string SettingsMiscellaneousStartupSettingsContent {
            get {
                return ResourceManager.GetString("SettingsMiscellaneousStartupSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Shapeshifter when Windows starts.
        /// </summary>
        public static string SettingsMiscellaneousStartupSettingsStartWithWindows {
            get {
                return ResourceManager.GetString("SettingsMiscellaneousStartupSettingsStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup settings.
        /// </summary>
        public static string SettingsMiscellaneousStartupSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsMiscellaneousStartupSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string SettingsMiscellaneousTitle {
            get {
                return ResourceManager.GetString("SettingsMiscellaneousTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you can configure how much memory Shapeshifter consumes by enabling or disabling Flamefusion&apos;s Incineration technology.
        ///
        ///Note that while enabling this will decrease memory consumption greatly, it might slow down or add unexpected behavior in Shapeshifter..
        /// </summary>
        public static string SettingsPerformanceAndStabilityMemoryConsumptionContent {
            get {
                return ResourceManager.GetString("SettingsPerformanceAndStabilityMemoryConsumptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory consumption.
        /// </summary>
        public static string SettingsPerformanceAndStabilityMemoryConsumptionTitle {
            get {
                return ResourceManager.GetString("SettingsPerformanceAndStabilityMemoryConsumptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance &amp; stability.
        /// </summary>
        public static string SettingsPerformanceAndStabilityTitle {
            get {
                return ResourceManager.GetString("SettingsPerformanceAndStabilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Flamefusion&apos;s Incineration memory cleanup technology.
        /// </summary>
        public static string SettingsPerformanceAndStabilityUseIncineration {
            get {
                return ResourceManager.GetString("SettingsPerformanceAndStabilityUseIncineration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayIconContextMenuExit {
            get {
                return ResourceManager.GetString("TrayIconContextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us feedback.
        /// </summary>
        public static string TrayIconContextMenuFeedback {
            get {
                return ResourceManager.GetString("TrayIconContextMenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flamefusion&apos;s Facebook page.
        /// </summary>
        public static string TrayIconContextMenuFlamefusionFacebookPage {
            get {
                return ResourceManager.GetString("TrayIconContextMenuFlamefusionFacebookPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TrayIconContextMenuSettings {
            get {
                return ResourceManager.GetString("TrayIconContextMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapeshifter&apos;s Facebook page.
        /// </summary>
        public static string TrayIconContextMenuShapeshifterFacebookPage {
            get {
                return ResourceManager.GetString("TrayIconContextMenuShapeshifterFacebookPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help translate Shapeshifter.
        /// </summary>
        public static string TrayIconContextMenuTranslate {
            get {
                return ResourceManager.GetString("TrayIconContextMenuTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re just a few seconds from experiencing the best clipboard manager on earth. However, it&apos;s quite important that we have your attention for just a moment. Shapeshifter can be used through different methods. Please select the method that is most suitable for you below..
        /// </summary>
        public static string WelcomeContent {
            get {
                return ResourceManager.GetString("WelcomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External mode allows you to manage items by clicking the Shapeshifter taskbar icon (Windows 7 or later)..
        /// </summary>
        public static string WelcomeExternalModeContent {
            get {
                return ResourceManager.GetString("WelcomeExternalModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External mode.
        /// </summary>
        public static string WelcomeExternalModeTitle {
            get {
                return ResourceManager.GetString("WelcomeExternalModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started!.
        /// </summary>
        public static string WelcomeGetStarted {
            get {
                return ResourceManager.GetString("WelcomeGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated mode allows you to paste and manage items with CTRL + V (by holding it down)..
        /// </summary>
        public static string WelcomeIntegratedModeContent {
            get {
                return ResourceManager.GetString("WelcomeIntegratedModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated mode.
        /// </summary>
        public static string WelcomeIntegratedModeTitle {
            get {
                return ResourceManager.GetString("WelcomeIntegratedModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mixed mode combines the integrated mode and the external mode (Windows 7 or later)..
        /// </summary>
        public static string WelcomeMixedModeContent {
            get {
                return ResourceManager.GetString("WelcomeMixedModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed mode.
        /// </summary>
        public static string WelcomeMixedModeTitle {
            get {
                return ResourceManager.GetString("WelcomeMixedModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Shapeshifter!.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
